title: Super Chicken Construction
email: bo@turnbows.org
description: > # this means to ignore newlines until "baseurl:"
  The story of building a little boat named Super Chicken.

github_username:  boturnbow

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
